const programming = process.env.SF_PROGRAMMING_ID || null;
const content = process.env.SF_CONTENT_ID || null;
const implementation =  process.env.SF_IMPLEMENTATION_ID || null; //  tasks@lobstermarketing.com

let errDesc = {
    1:   {title: "Pages returned 5XX status code", sendTo: programming, include:false},
    2:   {title: "Pages returned 4XX status code", sendTo: implementation, include:true},
    3:   {title: "Pages don't have title tags", sendTo: implementation, include:true},
    4:   {title: "Pages are blocked from crawling", sendTo:implementation, include:false},
    6:   {title: "Issues with duplicate title tags", sendTo: implementation, include:false},
    7:   {title: "Pages have duplicate content issues", sendTo:implementation, include:false},
    8:   {title: "Internal links are broken", sendTo: implementation, include:true},
    9:   {title: "Pages couldn't be crawled", sendTo: programming, include:false},
    10:  {title: "Pages couldn't be crawled (DNS resolution issues)", sendTo: programming, include:false },
    12:  {title: "External links are broken", sendTo: implementation, include:true},
    11:  {title: "Pages couldn't be crawled (incorrect URL formats)", sendTo: implementation, include:false},
    13:  {title: "Internal images are broken", sendTo: implementation, include:false},
    14:  {title: "External images are broken", sendTo: implementation, include:true},    
    15:  {title: "Pages have duplicate meta descriptions", sendTo: implementation, include:false},
    16:  {title: "Robots.txt file has format errors", sendTo: programming, include:false},
    17:  {title: "Sitemap.xml files have format errors ", sendTo: programming, include:false},
    18:  {title: "Incorrect pages found in sitemap.xml", sendTo: implementation, include:false},
    19:  {title: "Pages have a WWW resolve issue ", sendTo: programming, include:false},
    20:  {title: "Pages have no viewport tag", sendTo: programming, include:false},
    21:  {title: "Pages have too large HTML size", sendTo: implementation, include:false},
    22:  {title: "AMP pages have no canonical tag", sendTo: implementation, include:false},
    23:  {title: "Issues with hreflang values ", sendTo: implementation, include:false},
    24:  {title: "Hreflang conflicts within page source code", sendTo: programming, include:false},
    25:  {title: "Issues with incorrect hreflang links", sendTo: implementation, include:false},
    26:  {title: "Non-secure pages ", sendTo: programming, include:false},
    27:  {title: "Issues with expiring or expired certificate", sendTo: programming, include:false},
    28:  {title: "Issues with old security protocol", sendTo: programming, include:false},
    29:  {title: "Issues with incorrect certificate name", sendTo: programming, include:false},
    30:  {title: "Issue with mixed content", sendTo: programming, include:false },
    31:  {title: "Links lead to HTTP pages for HTTPS site", sendTo: implementation, include:false},
    32:  {title: "No redirect or canonical to HTTPS homepage from HTTP version", sendTo: implementation, include:false},
    33:  {title: "redirect chains and loops ", sendTo: implementation, include:false},
    34:  {title: "AMP HTML issues", sendTo: implementation, include:false},
    35:  {title: "AMP style and layout issues", sendTo: programming, include:false},
    36:  {title: "AMP templating issues", sendTo: programming, include:false},
    38:  {title: "Pages with a broken canonical link", sendTo: implementation, include:true},
    39:  {title: "Pages have multiple canonical URLs", sendTo: programming, include:false},
    40:  {title: "Pages have a meta refresh tag", sendTo: programming, include:false},
    41:  {title: "Issues with broken internal JavaScript and CSS files", sendTo: programming, include:false},
    42:  {title: "Subdomains don’t support secure encryption algorithms", sendTo: programming, include:false},
    43:  {title: "Sitemap.xml files are too large", sendTo: programming, include:false},
    44:  {title: "Links couldn't be crawled (incorrect URL formats)", sendTo: implementation, include:false},
    45:  {title: "Structured data items are invalid", sendTo: programming, include:false},
    101: {title: "Don't have enough text within the title tags", sendTo: implementation, include:false},
    102: {title: "Too much text within the title tags", sendTo: programming, include:false},
    103: {title: "Pages don't have an h1 heading ", sendTo: implementation, include:false},
    104: {title: "Pages have more than one H1 tag ", sendTo: implementation, include:false},
    105: {title: "Duplicate H1 and title tags", sendTo: implementation, include:false},
    106: {title: "Pages don't have meta descriptions", sendTo: implementation, include:true},
    108: {title: "Pages have too many on-page links ", sendTo: implementation, include:false},
    109: {title: "URLs with a temporary redirect ", sendTo: implementation, include:false},
    110: {title: "Images don't have alt attributes", sendTo: implementation, include:false},
    111: {title: "Pages have slow load speed", sendTo: programming, include:false},
    112: {title: "Low text-HTML ratio", sendTo: content, include:false},
    113: {title: "Pages have too many parameters in their URLs", sendTo: implementation, include:false},
    114: {title: "Pages have no hreflang and lang attributes ", sendTo: programming, include:false},
    115: {title: "Pages don't have character encoding declared ", sendTo: programming, include:false},
    116: {title: "Pages don't have doctype declared", sendTo: programming, include:false},
    117: {title: "Pages have a low word count", sendTo: content, include:false},
    121: {title: "Pages contain frames", sendTo: programming, include:false},
    122: {title: "Pages have underscores in the URL", sendTo: implementation, include:true},
    123: {title: "Outgoing internal links contain nofollow attribute", sendTo: implementation, include:false},
    124: {title: "Sitemap.xml not indicated in robots.txt ", sendTo: programming, include:false},
    125: {title: "Sitemap.xml not found", sendTo: programming, include:false},
    126: {title: "Homepage does not use HTTPS encryption ", sendTo: programming, include:false},
    127: {title: "Subdomains don't support SNI", sendTo: programming, include:false},
    128: {title: "Links on HTTPS pages leads to HTTP page", sendTo: implementation, include:false},
    129: {title: "Uncompressed pages", sendTo: programming, include:false},
    131: {title: "Issues with uncompressed JavaScript and CSS files", sendTo: programming, include:false},
    132: {title: "Issues with uncached JavaScript and CSS files", sendTo: programming, include:false},
    133: {title: "Pages have a JavaScript and CSS total size that is too large", sendTo: programming, include:false},
    134: {title: "Pages use too many JavaScript and CSS files ", sendTo: programming, include:false},
    135: {title: "Unminified JavaScript and CSS files", sendTo: programming, include:false},
    136: {title: "Page URLs are longer than 200 characters", sendTo: implementation, include:false},
    201: {title: "Link URLs are too long", sendTo: implementation, include:false},
    202: {title: "Outgoing external links contain nofollow attributes", sendTo: implementation, include:false},
    203: {title: "Robots.txt not found", sendTo: programming, include:false},
    204: {title: "Pages have hreflang language mismatch issues ", sendTo: programming, include:false},
    205: {title: "Subdomain doesn't support HSTS", sendTo: programming, include:false},
    207: {title: "Orphaned pages in sitemaps", sendTo: programming, include:false},
    209: {title: "Pages blocked by X-Robots-Tag: noindex HTTP header ", sendTo: programming, include:false},
    212: {title: "Pages need more than 3 clicks to be reached", sendTo: implementation, include:false},
    213: {title: "Pages have only one incoming internal link", sendTo: implementation, include:false},
    214: {title: "URLs with a permanent redirect", sendTo: implementation, include:false},
    216: {title: "Links on this page have no anchor text", sendTo: implementation, include:false},
    217: {title: "Links on this page have non-descriptive anchor text", sendTo: implementation, include:false},
    218: {title: "Links to external pages or resources returned a 403 HTTP status code", sendTo: implementation, include:true},

}

module.exports = errDesc;